[package]
name = "color_object"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MySocial = { local = "../../../crates/mys-framework/packages/mys-framework" }

[addresses]
color_object = "0x0"
