[package]
name = "mydata"
version = "0.0.1"
published-at = "0x5ea1"
edition = "2024"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
MySocial = { local = "../mys-framework" }

[addresses]
mydata = "0x5ea1"

