---
- name: Add a mys user
  ansible.builtin.user:
    name: mys
    shell: /bin/bash

- name: Create mys directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "mys"
    group: "mys"
    mode: 0755
  loop:
    - /opt/mys/bin
    - /opt/mys/config
    - /opt/mys/db
    - /opt/mys/key-pairs

- name: Copy validator configuration file
  copy:
    src: "{{ node_config }}"
    dest: /opt/mys/config/validator.yaml
    owner: "mys"
    group: "mys"
    mode: 0644

- name: Copy genesis.blob
  copy:
    src: "{{ genesis_blob }}"
    dest: /opt/mys/config/genesis.blob
    owner: "mys"
    group: "mys"
    mode: 0644

- name: Copy protocol.key
  copy:
    src: "{{ keypair_path }}protocol.key"
    dest: /opt/mys/key-pairs/protocol.key
    owner: "mys"
    group: "mys"
    mode: 0600

- name: Copy network.key
  copy:
    src: "{{ keypair_path }}network.key"
    dest: /opt/mys/key-pairs/network.key
    owner: "mys"
    group: "mys"
    mode: 0600

- name: Copy worker.key
  copy:
    src: "{{ keypair_path }}worker.key"
    dest: /opt/mys/key-pairs/worker.key
    owner: "mys"
    group: "mys"
    mode: 0600

- name: Stop mys-node
  systemd:
    name: mys-node
    state: stopped
  ignore_errors: yes

- name: Remove authorities directory
  file:
    state: absent
    path: "/opt/mys/db/authorities_db"
  when: reset_db == true

- name: Remove consensus directory
  file:
    state: absent
    path: "/opt/mys/db/consensus_db"
  when: reset_db == true

- name: Place binary
  ansible.builtin.get_url:
    url: "https://releases.mys.io/{{ mys_release }}/mys-node"
    dest: /opt/mys/bin/mys-node
    force: true
    mode: "0755"

- name: Copy mys-node systemd service file
  copy:
    src: "../files/mys-node.service"
    dest: /etc/systemd/system/mys-node.service

- name: Reload mys-node systemd service file
  ansible.builtin.systemd:
    name: mys-node
    state: reloaded

- name: Start mys-node service
  systemd:
    name: mys-node
    state: started
  when: start_mys == true
