[package]
name = "BridgedUSDC"
version = "0.0.1"
published-at = "0x0"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
MySocial = { local = "../mys-framework" }

[addresses]
bridged_usdc = "0x0"
