[package]
name = "mys-field-count"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
mys-field-count-derive.workspace = true
