# config.yaml format:

# URL of the remote store
remote_store_url: https://storage.googleapis.com/mysocial-testnet-checkpoints
# URL for MySocial RPC  
mys_rpc_url: http://fullnode.testnet.mysocial.network:8082
# URL for Ethereum RPC
eth_rpc_url: https://base-sepolia.g.alchemy.com/v2/dP5ANdv4tQc7ldy_stPvRTQWtO0J3KS5
# URL for Ethereum WebSocket RPC
eth_ws_url: wss://base-sepolia.g.alchemy.com/v2/CTLwBwcLSgKAIYyujNUnfn6ThiSLHVNS
# Database connection URL
db_url: postgresql://postgres:ETTZFVeKtrUyuVDlYKzGQqYCjINNjbWH@postgres-6eso.railway.internal:5432/railway
# Path to the checkpoints (optional)
# checkpoints_path: <path>
# Number of concurrent operations
concurrency: 1
# MySocial bridge genesis checkpoint for testnet
mys_bridge_genesis_checkpoint: 5633034
# Ethereum bridge genesis block
eth_bridge_genesis_block: 34790000
# Ethereum to MySocial bridge contract address
eth_mys_bridge_contract_address: 0xA18D9Dc3ef3A23A53C3F3Ce643f1c0b935772F0A
# Client metric port
metric_port: 9090
