# config.yaml format:

# URL of the remote store
remote_store_url: https://mysocial-testnet-checkpoints.storage.googleapis.com
# URL for MySocial RPC  
mys_rpc_url: http://fullnode.testnet.mysocial.network:8082
# URL for Ethereum RPC
eth_rpc_url: https://base-sepolia.g.alchemy.com/v2/dP5ANdv4tQc7ldy_stPvRTQWtO0J3KS5
# URL for Ethereum WebSocket RPC
eth_ws_url: wss://base-sepolia.g.alchemy.com/v2/CTLwBwcLSgKAIYyujNUnfn6ThiSLHVNS
# Database connection URL
db_url: postgresql://postgres:ETTZFVeKtrUyuVDlYKzGQqYCjINNjbWH@postgres-6eso.railway.internal:5432/railway
# Path to the checkpoints (optional)
# checkpoints_path: <path>
# Number of concurrent operations
concurrency: 100
# MySocial bridge genesis checkpoint for testnet (updated for new bridge deployment)
mys_bridge_genesis_checkpoint: 0
# Ethereum bridge genesis block (updated for new bridge deployment Dec 14)
eth_bridge_genesis_block: 36260727
# Ethereum to MySocial bridge contract address
eth_mys_bridge_contract_address: 0xE924C53019c5c105fBD126f01A611B830613165D
# Client metric port
metric_port: 9090
