[package]
name = "mys-transactional-test-runner"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for MySocial platform"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
bimap.workspace = true
clap.workspace = true
eyre.workspace = true
http.workspace = true
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
tempfile.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
criterion.workspace = true
tracing.workspace = true

fastcrypto.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-symbol-pool.workspace = true
move-transactional-test-runner.workspace = true
telemetry-subscribers.workspace = true

move-stdlib = { path = "../../external-crates/move/crates/move-stdlib" }
move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }

simulacrum.workspace = true
mys-graphql-rpc.workspace = true
mys-rpc-api.workspace = true
mys-swarm-config.workspace = true
mys-config.workspace = true
mys-core.workspace = true
mys-framework.workspace = true
mys-protocol-config.workspace = true
mys-types.workspace = true
mys-json-rpc-types.workspace = true
mys-json-rpc.workspace = true
mys-json-rpc-api.workspace = true
mys-framework-snapshot.workspace = true
mys-storage.workspace = true
typed-store.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true
