[package]
name = "mys-oracle"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MySocial = { git = "https://github.com/MystenLabs/mys.git", subdir = "crates/mys-framework/packages/mys-framework", rev = "9d0fba4a490e1cf80101bbd4019c7bb1ccfce99b" }

[addresses]
oracle = "0x0"
mys = "0x2"
