[package]
name = "MySocialContracts"
version = "0.0.1"
published-at = "0xd880"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
MySocial = { local = "../mys-framework" }
DeepBook = { local = "../deepbook" }
seal = { local = "../seal" }

[addresses]
mys_social = "0xd880"
