[package]
name = "bls_signature"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MySocial = { local = "../../../../crates/mys-framework/packages/mys-framework" }

[addresses]
bls_signature = "0x0"
