[package]
name = "mys-deepbook-indexer"
version = "0.1.0"
authors = ["The Social Proof Foundation <brandon@socialproof.foundation>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive", "rc"] }
tap = "1.0.1"
diesel = { version = "2.2", features = ["serde_json"] }
diesel-async = { version = "0.5", features = ["bb8", "postgres"] }
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.71"
futures = "0.3.28"
async-trait = "0.1.61"
bcs = "0.1.4"
clap = { version = "4.4", features = ["derive", "wrap_help"] }
mysten-metrics = { path = "../mysten-metrics" }
prometheus = "0.13.3"
serde_yaml = "0.8.26"
mys-sdk = { path = "../mys-sdk" }
mys-json-rpc-types = { path = "../mys-json-rpc-types" }
mys-data-ingestion-core = { path = "../mys-data-ingestion-core" }
mys-types = { path = "../mys-types" }
telemetry-subscribers = { path = "../telemetry-subscribers" }
tracing = "0.1.37"
backoff = { version = "0.4.0", features = ["futures", "futures-core", "pin-project-lite", "tokio", "tokio_1"] }
mys-config = { path = "../mys-config" }
mys-indexer-builder = { path = "../mys-indexer-builder" }
tempfile = "3.3.0"
axum = { version = "0.7", default-features = false, features = ["macros", "tokio", "http1", "http2", "json", "matched-path", "original-uri", "form", "query", "ws"] }
tower-http = { version = "0.5", features = ["cors", "full", "trace", "set-header", "propagate-header"] }
bigdecimal = { version = "0.4.5" }
serde_json = { version = "1.0", features = ["preserve_order"] }

[dev-dependencies]
hex-literal = "0.3.4"

[[bin]]
name = "mys-deepbook-indexer"
path = "src/main.rs"
