[package]
name = "mys-test-transaction-builder"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
bcs.workspace = true

shared-crypto.workspace = true
mys-genesis-builder.workspace = true
mys-move-build.workspace = true
mys-sdk.workspace = true
mys-types.workspace = true

move-core-types.workspace = true
