[package]
name = "MyUSD"
version = "0.0.1"
published-at = "0x75d6"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
MySocial = { local = "../mys-framework" }

[addresses]
myusd = "0x75d6"
