[package]
name = "mys-indexer-alt-framework"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
backoff.workspace = true
bb8 = "0.8.5"
bytes.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["env"] }
diesel = { workspace = true, features = ["chrono"] }
diesel-async = { workspace = true, features = ["bb8", "postgres", "async-connection-wrapper"] }
diesel_migrations.workspace = true
futures.workspace = true
pin-project-lite.workspace = true
prometheus.workspace = true
object_store.workspace = true
serde_json.workspace = true
rand.workspace = true
scoped-futures.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, optional = true }
url.workspace = true

mys-field-count.workspace = true
mys-futures.workspace = true
mys-indexer-alt-framework-store-traits.workspace = true
mys-indexer-alt-metrics.workspace = true
mys-rpc.workspace = true
mys-sdk-types.workspace = true
mys-rpc-api.workspace = true
mys-storage.workspace = true
mys-types.workspace = true
prost.workspace = true
prost-types.workspace = true
zstd.workspace = true

mys-pg-db = { workspace = true, optional = true }

[dev-dependencies]
telemetry-subscribers.workspace = true
wiremock.workspace = true
mys-pg-db.workspace = true
dashmap.workspace = true

mys-synthetic-ingestion.workspace = true

[features]
default = ["cluster"]
cluster = ["dep:tracing-subscriber", "postgres"]
postgres = ["dep:mys-pg-db"]
