[package]
name = "mys-adapter-v2"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Adapter and accompanying CLI for local mys development"
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
bcs.workspace = true
leb128.workspace = true
tracing.workspace = true
serde.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
move-vm-types.workspace = true

move-bytecode-verifier = { path = "../../../external-crates/move/move-execution/v2/crates/move-bytecode-verifier", package = "move-bytecode-verifier-v2" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/v2/crates/move-vm-runtime", package = "move-vm-runtime-v2" }
move-vm-profiler = { path = "../../../external-crates/move/crates/move-vm-profiler" }
mys-move-natives = { path = "../mys-move-natives", package = "mys-move-natives-v2" }
mys-verifier = { path = "../mys-verifier", package = "mys-verifier-v2" }

mys-macros.workspace = true
mys-protocol-config.workspace = true
mys-types.workspace = true
parking_lot.workspace = true

[dev-dependencies]
move-package.workspace = true

[features]
tracing = [
    "mys-types/tracing",
    "move-vm-runtime/tracing",
    "move-vm-profiler/tracing",
    "move-vm-config/tracing",
]
