[package]
name = "mys-transaction-checks"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
once_cell.workspace = true
mys-macros.workspace = true
mys-config.workspace = true
mys-protocol-config.workspace = true
mys-types.workspace = true
tracing.workspace = true
mys-execution.workspace = true
fastcrypto-zkp.workspace = true
