server-listen-port: 8080
metrics-port: 9090
bridge-authority-key-path: /tmp/bridge_key_validator_2
run-client: false
approved-governance-actions:
  - AddTokensOnMysAction:
      nonce: 0
      chain_id: MysCustom
      native: true
      token_ids: [0]
      token_type_names:
        - Struct:
            address: "0x0000000000000000000000000000000000000000000000000000000000000002"
            module: "mys"
            name: "MYS"
            type_params: []
      token_prices: [47000]
db-path: /app/bridge_db_2

mys:
  mys-rpc-url: "http://fullnode.testnet.mysocial.network:8082"
  mys-bridge-chain-id: 2

eth:
  eth-rpc-url: "${ETH_RPC_URL}"
  eth-bridge-proxy-address: "${ETH_BRIDGE_PROXY_ADDRESS}"
  eth-bridge-chain-id: 12
  eth-contracts-start-block-fallback: 34770000

metrics:
  push-url: "https://bridge-metrics.testnet.mysocial.network:8443/publish/metrics"
