server-listen-port: 8082
metrics-port: 9092
bridge-authority-key-path: /tmp/bridge_key
run-client: false
approved-governance-actions:
  - AddTokensOnMysAction:
      nonce: 0
      chain_id: 2
      native: true
      token_ids: [0]
      token_type_names: ["0x2::mys::MYS"]
      token_prices: [4450]

mys:
  mys-rpc-url: "http://fullnode.testnet.mysocial.network:8082"
  mys-bridge-chain-id: 2

eth:
  eth-rpc-url: "https://base-sepolia.g.alchemy.com/v2/dP5ANdv4tQc7ldy_stPvRTQWtO0J3KS5"
  eth-bridge-proxy-address: "0x3b80bb0443D731ee5176ec89568fDFe8eB0aAFdd"
  eth-bridge-chain-id: 12
  eth-contracts-start-block-fallback: 31901989

metrics:
  push-url: "https://bridge-metrics.testnet.mysocial.network:8443/publish/metrics"
