[build]
builder = "dockerfile"
dockerfilePath = "crates/mys-analytics-indexer/Dockerfile"

[deploy]
startCommand = "mys-analytics-indexer"
healthcheckPath = "/metrics"
healthcheckTimeout = 60

[variables]
# Logging configuration
RUST_LOG = "info,mys_analytics_indexer=debug"

# Core configuration
REST_URL = "https://fullnode.mainnet.mysocial.network:9000"
FILE_TYPE = "checkpoint"
CHECKPOINT_INTERVAL = "10000" 