[package]
name = "Bridge"
version = "0.0.1"
published-at = "0xb"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
MySocial = { local = "../mys-framework" }
MySocialSystem = { local = "../mys-system" }

[addresses]
bridge = "0xb"

